version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # login with credentials stored in the UI
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t alexmarchant/oscars-2019-spa:latest .

      # deploy the image
      - run: docker push alexmarchant/oscars-2019-spa:latest

      # install kubectl
      - run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl

      # spit kubeconfig out to a file
      - run: echo "${KUBECONFIG}" | base64 --decode >> kubeconfig.yml

      # tell kubernetes to pull latest image
      - run: |
          kubectl --kubeconfig="kubeconfig.yml" \
            patch deployment tracker-spa -p \
            "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
